/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package user_interface;

import com.google.gson.JsonElement;
import com.jakubwawak.track.connector.Connector;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.util.logging.Level;
import java.util.logging.Logger;
import maintenence.Parser;

/**
 *Window for loggin user
 * @author kubaw
 */
public class login_window extends javax.swing.JDialog {

    /**
     * Creates new form login_window
     */
    Connector connector;
    int mode;
    public login_window(java.awt.Frame parent, boolean modal,Connector connector,int mode) {
        super(parent, modal);
        this.connector = connector;
        this.mode = mode;
        initComponents();
        this.setLocationRelativeTo(null);
        label_version.setText(this.connector.version);
        label_buildnumber.setText(this.connector.bulid);
        setVisible(true);
    }
    
    /**
     * Function for field validation
     * @return 
     */
    boolean validate_fields(){
        return !field_login.getText().equals("") && !field_password.getText().equals("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        field_login = new javax.swing.JTextField();
        button_login = new javax.swing.JButton();
        label_version = new javax.swing.JLabel();
        label_buildnumber = new javax.swing.JLabel();
        field_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Track Client");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Login:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password:");

        field_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        button_login.setText("Login");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        label_version.setText("version");

        label_buildnumber.setText("build number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_login)
                            .addComponent(field_password, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_version)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_buildnumber)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_version)
                    .addComponent(label_buildnumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        if ( validate_fields() ){
            try {
                JsonElement response = connector.user_login(field_login.getText(),field_password.getText());
                if (response != null){
                    Parser parser = new Parser(response);
                    if(parser.get_int("user_id") == -6){
                        new message_window(this,true,"App token not found.","APPTOKEN_ERROR");
                    }
                    else if (parser.get_int("user_id") == -5){
                        new message_window(this,true,"Wrong password or login. Authorization failed.","AUTH_ERROR");
                    }
                    else if (parser.get_int("user_id") == -1){
                        new message_window(this,true,"No user with that login or password found","NOUSER_ERROR");
                    }
                    else{
                        new message_window(this,true,"Welcome back "+parser.get_string("user_name")+"!","welcome!");
                        //login successfull
                        if (mode == 0)
                            new main_window(connector);
                        dispose();
                    }
                }
                else{
                    
                }
            } catch (UnirestException ex) {
                new message_window(this,true,"ERROR\n"+ex.toString(),"ERROR");
            }
            
        }
        else{
            new message_window(this,true,"Wrong login or password","ERROR");
        }
    }//GEN-LAST:event_button_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login;
    private javax.swing.JTextField field_login;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_buildnumber;
    private javax.swing.JLabel label_version;
    // End of variables declaration//GEN-END:variables
}
