/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package user_interface;

/**
 *Window for showing messages
 * @author kubaw
 */
public class message_window extends javax.swing.JDialog {

    /**
     * Creates new form message_window
     */
    public message_window(java.awt.Frame parent, boolean modal,String message,String optional_title) {
        super(parent, modal);
        initComponents();
        if ( !optional_title.equals("") ){
            setTitle("Message "+optional_title);
        }
        field_message.setText(message);
        field_message.setEditable(false);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public message_window(javax.swing.JFrame parent, boolean modal,String message,String optional_title) {
        super(parent, modal);
        initComponents();
        if ( !optional_title.equals("") ){
            setTitle("Message "+optional_title);
        }
        field_message.setText(message);
        field_message.setEditable(false);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public message_window(javax.swing.JDialog parent, boolean modal,String message,String optional_title) {
        super(parent, modal);
        initComponents();
        if ( !optional_title.equals("") ){
            setTitle("Message "+optional_title);
        }
        field_message.setText(message);
        field_message.setEditable(false);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    public message_window(String message,String optional_title) {
        initComponents();
        if ( !optional_title.equals("") ){
            setTitle("Message "+optional_title);
        }
        field_message.setText(message);
        field_message.setEditable(false);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_ok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_message = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Message");

        button_ok.setText("Ok");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        field_message.setColumns(20);
        field_message.setRows(5);
        jScrollPane1.setViewportView(field_message);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(button_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_ok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        dispose();
    }//GEN-LAST:event_button_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ok;
    private javax.swing.JTextArea field_message;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
