/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package user_interface;

import com.jakubwawak.track.connector.Connector;
import com.jakubwawak.track.connector.ToDo_Connector;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import maintenence.Parser;

/**
 *Window for adding todo objects
 * @author jakubwawak
 */
public class todoadd_window extends javax.swing.JDialog {

    /**
     * Creates new form todoadd_window
     */
    Connector connector;
    
    /**
     * Constructor
     * @param connector 
     */
    public todoadd_window(javax.swing.JFrame parent ,boolean modal,Connector connector) {
        super(parent,modal);
        initComponents();
        this.connector = connector;
        this.setLocationRelativeTo(parent);
        load_window();
        setVisible(true);
    }
    
    /**
     * Function for loading window icon
     */
    void load_window_icon(){
        try{
            ImageIcon img = new ImageIcon("track_icon.png");
            this.setIconImage(img.getImage());
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * Function for loading window content
     */
    void load_window(){
        load_window_icon();
    }
    
    /**
     * Function for validating fields 
     */
    boolean validate_fields(){
        return !todo_title.getText().equals("") && !todo_desc.getText().equals("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        todo_title = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        todo_desc = new javax.swing.JTextArea();
        check_important = new javax.swing.JCheckBox();
        combobox_colour = new javax.swing.JComboBox<>();
        button_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add new to do ");

        todo_title.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        todo_title.setText("Title");

        todo_desc.setColumns(20);
        todo_desc.setRows(5);
        todo_desc.setText("Description\n");
        jScrollPane1.setViewportView(todo_desc);

        check_important.setSelected(true);
        check_important.setText("Important");

        combobox_colour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Yellow", "Green", "Blue" }));

        button_add.setText("Add");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(todo_title)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(combobox_colour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(check_important)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todo_title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_important)
                    .addComponent(combobox_colour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(button_add)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        ToDo_Connector tdc = new ToDo_Connector(connector);
        if (validate_fields()){
            int todo_colour = combobox_colour.getSelectedIndex()+1;
            int todo_impor = -1;
            if (check_important.isSelected()){
                todo_impor = 1;
            }
            else{
                todo_impor = 0;
            }
            try {
                Parser parser = new Parser(tdc.add_todo(todo_title.getText(), todo_desc.getText(), todo_impor, todo_colour, this));
                if ( parser.get_int("flag") == 1){
                    new message_window(this,true,"Added todo!","");
                    dispose();
                }
            } catch (Exception ex) {
                new message_window(this,true,"Error loading todo! Check API log","API Error");
                dispose();
            }
        }
        else{
            new message_window(this,true,"Error parsing fields","ERROR");
        }
    }//GEN-LAST:event_button_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JCheckBox check_important;
    private javax.swing.JComboBox<String> combobox_colour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea todo_desc;
    private javax.swing.JTextField todo_title;
    // End of variables declaration//GEN-END:variables
}
