/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package ui_components;

import com.jakubwawak.track.connector.Connector;
import com.jakubwawak.track.connector.Project_Connector;
import com.mashape.unirest.http.exceptions.UnirestException;
import maintenence.Parser;
import user_interface.message_window;

/**
 *Window for adding member
 * @author jakubwawak
 */
public class addmember_window extends javax.swing.JDialog {

    
    Connector connector;
    int project_id;
    /**
     * Creates new form addmember_window
     */
    public addmember_window(java.awt.Frame parent, boolean modal,Connector connector,int project_id) {
        super(parent, modal);
        this.connector = connector;
        this.project_id = project_id;
        initComponents();
        this.setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_login = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        button_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add member");

        field_login.setText("jTextField1");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User login");

        button_add.setText("Add member");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_login)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_add)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        String user_input = field_login.getText();
        if ( !user_input.equals("") ){
            try {
                Parser parser = new Parser(connector.check_user_login(user_input, this));
                if ( parser.get_int("user_id") > 0 ){
                    Project_Connector pc = new Project_Connector(connector);
                    Parser parser1 = new Parser(pc.add_project_members(this, project_id, parser.get_int("user_id")));
                    if ( parser1.get_int("flag") == 2 ){
                        new message_window(this,true,"Member added","");
                        dispose();
                    }
                    else{
                        new message_window(this,true,"Error adding member","ERROR");
                    }
                }
            } catch (UnirestException ex) {
                new message_window(this,true,"Error\n"+ex.toString(),"ERROR");
                dispose();
            }
        }
        else{
            new message_window(this,true,"Error\n Wrong login","");
        }
    }//GEN-LAST:event_button_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JTextField field_login;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
