/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package ui_components;

import com.jakubwawak.track.connector.Connector;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Image;
import java.awt.Toolkit;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import maintenence.Parser;
import maintenence.Password_Validator;
import user_interface.login_window;
import user_interface.message_window;

/**
 *Window for changing password
 * @author kubaw
 */
public class changepassword_window extends javax.swing.JDialog {

    /**
     * Creates new form changepassword_window
     */
    Connector connector;
    public changepassword_window(java.awt.Frame parent, boolean modal,Connector connector) {
        super(parent, modal);
        this.connector = connector;
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * Function for validating fields
     * @return Boolean
     */
    int validate_fields(){
        if (!new_password.getText().equals("") && !new_password2.getText().equals("")
                && !old_password.getText().equals("")){
            if ( new_password.getText().equals(new_password2.getText())){
                if ( new_password.getText().length() <= 12)
                    return 1;
                return 3;
            }
            return 2;
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        old_password = new javax.swing.JPasswordField();
        new_password = new javax.swing.JPasswordField();
        new_password2 = new javax.swing.JPasswordField();
        button_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reset password");

        jLabel1.setText("Old password:");

        jLabel2.setText("New password:");

        jLabel3.setText("Re-enter new password:");

        button_reset.setText("Reset password");
        button_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(new_password2)
                            .addComponent(new_password, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(old_password))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(old_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(new_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(new_password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_reset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_resetActionPerformed
        switch(validate_fields()){
            case 1:
            {
                try {
                    //ready to reset password
                    Password_Validator pv = new Password_Validator(new_password.getText());
                    Password_Validator pv2 = new Password_Validator(old_password.getText());
                    Parser parser = new Parser(connector.user_resetpassword(pv2.hash(),pv.hash(), this));
                    
                    if ( parser.get_int("user_id") > 0 ){
                        new message_window(this,true,"Password value updated","");
                        dispose();
                    }
                    else if ( parser.get_int("user_id") == -5){
                        new message_window(this,true,"Password validation failed","");
                    }
                    else if ( parser.get_int("user_id") == -11){
                        new login_window(this,true,connector,1);
                    }
                    else{
                        new message_window(this,true,"Error. Check log data.","ERROR");
                    }
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(changepassword_window.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnirestException ex) {
                Logger.getLogger(changepassword_window.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
            case 2:
                new message_window(this,true,"New passwords doesn't match.","");
                break;
            case 3:
                new message_window(this,true,"Password length cannot be bigger than 12 signs","");
            case 0:
                new message_window(this,true,"Fields validation failed","");
                break;
        }
    }//GEN-LAST:event_button_resetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField new_password;
    private javax.swing.JPasswordField new_password2;
    private javax.swing.JPasswordField old_password;
    // End of variables declaration//GEN-END:variables
}
