/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package ui_components;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *Window for showing history
 * @author kubaw
 */
public class history_window extends javax.swing.JDialog {

    /**
     * Creates new form history_window
     */
    public history_window(java.awt.Frame parent, boolean modal,String title,ArrayList<String> content) {
        super(parent, modal);
        this.setTitle(title);
        initComponents();
        load_view(content);
        this.setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage("track_icon.ico");
        this.setIconImage(icon);
        setVisible(true);
    }
    
    public history_window(javax.swing.JDialog parent, boolean modal,String title,ArrayList<String> content) {
        super(parent, modal);
        this.setTitle(title);
        initComponents();
        load_view(content);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    /**
     * Function for loading
     */
    void load_view(ArrayList<String> data){
        DefaultListModel dlm = new DefaultListModel();
        dlm.addAll(data);
        list_history.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_history = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        list_history.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_history);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_history;
    // End of variables declaration//GEN-END:variables
}
