/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package ui_components;

import com.jakubwawak.track.connector.Connector;
import com.jakubwawak.track.connector.Issue_Connector;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import maintenence.Parser;
import user_interface.message_window;

/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */

/**
 *
 * @author kubaw
 */
public class issuedetails_window extends javax.swing.JDialog {

    /**
     * Creates new form issuedetails_window
     */
    Connector connector;
    int issue_id;
    public issuedetails_window(java.awt.Frame parent, boolean modal,Connector connector,int issue_id) throws UnirestException {
        super(parent, modal);
        this.connector = connector;
        this.issue_id = issue_id;
        initComponents();
        this.setLocationRelativeTo(null);
        load_window();
        setVisible(true);
    }
    
    /**
     * Function for loading window components
     */
    void load_window() throws UnirestException{
        Issue_Connector ic = new Issue_Connector(connector);
        Parser parser = new Parser(ic.issue_get(issue_id, this));
        Parser user = new Parser(connector.get_user(parser.get_int("user_id"), this));
        this.setTitle("Issue - "+parser.get_string("issue_name")+" - details");
        label_issuename.setText(parser.get_string("issue_name"));
        load_combobox(parser.get_int("issue_group"));
        label_status.setText(parser.get_string("issue_state"));
        label_owner.setText(user.get_string("user_login"));
        label_priority.setText(Integer.toString(parser.get_int("issue_priority")));
        label_projectid.setText(Integer.toString(parser.get_int("project_id")));
        field_desc.setText(parser.get_string("issue_desc"));
        field_desc.setEditable(false);
        
        switch(label_status.getText()){
            case "UNDONE":
                label_status.setForeground(Color.red);
                break;
            case "DONE":
                label_status.setForeground(Color.green);
                combobox_state.setEnabled(false);
                button_setdone.setEnabled(false);
                break;
        }
    }
    
    /**
     * Function for loading combobox
     */
    void load_combobox(int mode){
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        dcm.addElement("Untouched");
        dcm.addElement("Planned");
        dcm.addElement("In work");
        dcm.addElement("Done");
        combobox_state.setModel(dcm);
        combobox_state.setSelectedIndex(mode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_issuename = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        combobox_state = new javax.swing.JComboBox<>();
        button_update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        label_status = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_desc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_priority = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_owner = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_projectid = new javax.swing.JLabel();
        button_history = new javax.swing.JButton();
        button_setdone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_issuename.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label_issuename.setText("ISSUE NAME");

        jLabel1.setText("Actual state of the issue:");

        combobox_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        button_update.setText("Update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        jLabel2.setText("Issue status:");

        label_status.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_status.setText("STATUS");

        field_desc.setColumns(20);
        field_desc.setRows(5);
        jScrollPane1.setViewportView(field_desc);

        jLabel4.setText("Description:");

        jLabel5.setText("Issue priority:");

        label_priority.setText("priority");

        jLabel7.setText("Owner:");

        label_owner.setText("owner");

        jLabel9.setText("Connected to project:");

        label_projectid.setText("project_id");

        button_history.setText("Show issue history");
        button_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_historyActionPerformed(evt);
            }
        });

        button_setdone.setText("Set state do done");
        button_setdone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_setdoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_issuename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox_state, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_update, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)))
                                    .addComponent(jLabel9))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_projectid)
                                    .addComponent(label_priority)
                                    .addComponent(label_status)
                                    .addComponent(label_owner)))
                            .addComponent(button_history, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(button_setdone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_issuename, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combobox_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_update))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(label_status))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(label_priority))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(label_owner))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(label_projectid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_history)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_setdone)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        int issue_group = combobox_state.getSelectedIndex();
        try{
            Issue_Connector ic = new Issue_Connector(connector);
            Parser parser = new Parser(ic.update_group(issue_id, issue_group, this));
            if (parser.get_int("flag") == 1){
                new message_window(this,true,"Group state value updated","");
                load_window();
            }
        } catch (UnirestException ex) {
            new message_window(this,true,"Error\n"+ex.toString(),"ERROR");
        }
    }//GEN-LAST:event_button_updateActionPerformed

    private void button_setdoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_setdoneActionPerformed
        int issue_group = combobox_state.getSelectedIndex();
        try{
            Issue_Connector ic = new Issue_Connector(connector);
            Parser parser = new Parser(ic.update_group(issue_id, 3, this));
            if (parser.get_int("flag") == 1){
                new message_window(this,true,"Group state value updated","");
                load_window();
            }
        } catch (UnirestException ex) {
            new message_window(this,true,"Error\n"+ex.toString(),"ERROR");
        }
    }//GEN-LAST:event_button_setdoneActionPerformed

    private void button_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_historyActionPerformed
        Issue_Connector ic = new Issue_Connector(connector);
        try {
            Parser parser = new Parser(ic.load_issue_history(issue_id, this));
            new history_window(this,true,"History",parser.get_arraylist("view"));
        } catch (UnirestException ex) {
            new message_window(this,true,"Error\n"+ex.toString(),"ERROR");
        }
    }//GEN-LAST:event_button_historyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_history;
    private javax.swing.JButton button_setdone;
    private javax.swing.JButton button_update;
    private javax.swing.JComboBox<String> combobox_state;
    private javax.swing.JTextArea field_desc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_issuename;
    private javax.swing.JLabel label_owner;
    private javax.swing.JLabel label_priority;
    private javax.swing.JLabel label_projectid;
    private javax.swing.JLabel label_status;
    // End of variables declaration//GEN-END:variables
}
