/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package ui_components;

import com.jakubwawak.track.connector.Connector;
import com.jakubwawak.track.connector.Issue_Connector;
import com.jakubwawak.track.connector.Project_Connector;
import com.jakubwawak.track.connector.Task_Connector;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import maintenence.Parser;

/**
 *
 * @author kubaw
 */
public class projectdetails_window extends javax.swing.JDialog {

    /**
     * Creates new form projectdetails_window
     */
    Connector connector;
    int project_id;
    public projectdetails_window(java.awt.Frame parent, boolean modal,Connector connector,int project_id) throws UnirestException {
        super(parent, modal);
        this.connector = connector;
        this.project_id = project_id;
        initComponents();
        this.setLocationRelativeTo(null);
        load_window();
        setVisible(true);
    }
    
    /**
     * Function for loading window data
     */
    void load_window() throws UnirestException{
        load_project_data();
        load_tasks();
        load_issues();
    }
    
    /**
     * Function for loading project data
     */
    void load_project_data() throws UnirestException{
        Project_Connector pc = new Project_Connector(connector);
        Parser parser = new Parser(pc.load_project(project_id, this));
        field_name.setText(parser.get_string("project_name"));
        field_desc.setText(parser.get_string("project_desc"));
        field_projectid.setText("Project ID: "+Integer.toString(parser.get_int("project_id")));
        Parser user_parser = new Parser(connector.get_user(parser.get_int("user_id"), this));
        field_owner.setText("Owner: "+user_parser.get_string("user_login"));
        field_dateofcreation.setText("Date of creation: "+parser.get_string("project_creation_date"));
        field_desc.setEditable(false);
    }
    
    /**
     * Function for loading tasks
     * @throws UnirestException 
     */
    void load_tasks() throws UnirestException{
        DefaultListModel dlm = new DefaultListModel();
        Task_Connector tc = new Task_Connector(connector);
        Parser parser = new Parser(tc.load_task_glances(project_id, this));
        dlm.addAll(parser.get_arraylist("view"));
        list_tasks.setModel(dlm);
    }
    
    void load_issues() throws UnirestException{
        DefaultListModel dlm = new DefaultListModel();
        Issue_Connector ic = new Issue_Connector(connector);
        Parser parser = new Parser(ic.load_issues_glances(project_id, this));
        dlm.addAll(parser.get_arraylist("view"));
        list_issues.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_desc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        field_owner = new javax.swing.JLabel();
        field_projectid = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_tasks = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_issues = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        field_dateofcreation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Project Details");

        field_name.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        field_name.setText("Project Name");

        field_desc.setColumns(20);
        field_desc.setRows(5);
        jScrollPane1.setViewportView(field_desc);

        jLabel2.setText("Description");

        field_owner.setText("Owner:");

        field_projectid.setText("Project ID:");

        list_tasks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_tasks);

        jLabel5.setText("Connected tasks:");

        list_issues.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(list_issues);

        jLabel6.setText("Connected issues:");

        field_dateofcreation.setText("Date of creation:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(field_projectid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field_owner, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(field_dateofcreation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_owner)
                    .addComponent(field_projectid))
                .addGap(18, 18, 18)
                .addComponent(field_dateofcreation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel field_dateofcreation;
    private javax.swing.JTextArea field_desc;
    private javax.swing.JLabel field_name;
    private javax.swing.JLabel field_owner;
    private javax.swing.JLabel field_projectid;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> list_issues;
    private javax.swing.JList<String> list_tasks;
    // End of variables declaration//GEN-END:variables
}
