/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package ui_components;

import com.jakubwawak.track.connector.Connector;
import com.jakubwawak.track.connector.ToDo_Connector;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.util.logging.Level;
import java.util.logging.Logger;
import maintenence.Parser;
import user_interface.message_window;

/**
 *Window for changing todo state
 * @author jakubwawak
 */
public class todostate_window extends javax.swing.JDialog {

    /**
     * Creates new form todostate_window
     */
    Connector connector;
    int todo_id;
    public todostate_window(javax.swing.JFrame parent, boolean modal,Connector connector,int todo_id) {
        super(parent, modal);
        this.connector = connector;
        this.todo_id = todo_id;
        this.connector = connector;
        initComponents();
        this.setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox_state = new javax.swing.JComboBox<>();
        button_set = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New todo state");

        combobox_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not done", "In work", "Done" }));

        button_set.setText("Set");
        button_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_setActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combobox_state, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_set, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_set, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(combobox_state))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_setActionPerformed
        ToDo_Connector tdc = new ToDo_Connector(connector);
        try{
            int todo_state = combobox_state.getSelectedIndex();
            Parser parser = new Parser(tdc.set_todo(todo_id, todo_state, this));
            if ( parser.get_int("flag") == 1 ){
                new message_window(this,true,"State updated","");
                dispose();
            }
            else{
                new message_window(this,true,"Error occured when state updating\nCheck API log","ERROR");
                dispose();
            }
        } catch (UnirestException ex) {
            new message_window(this,true,"Error\n"+ex.toString(),"");
            dispose();
        }
    }//GEN-LAST:event_button_setActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_set;
    private javax.swing.JComboBox<String> combobox_state;
    // End of variables declaration//GEN-END:variables
}
