/*
Jakub Wawak
kubawawak@gmail.com
all rights reseved
 */
package ui_components;

import com.jakubwawak.track.connector.Connector;
import com.mashape.unirest.http.exceptions.UnirestException;
import maintenence.Parser;
import user_interface.main_window;
import user_interface.message_window;

/**
 *Object for creating 2fa authentication
 * @author kubaw
 */
public class twofactorauth_window extends javax.swing.JDialog {

    Connector connector;
    /**
     * Creates new form twofactorauth_window
     */
    public twofactorauth_window(javax.swing.JDialog parent, boolean modal,Connector connector) {
        super(parent, modal);
        this.connector = connector;
        initComponents();
        this.setLocationRelativeTo(parent);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_2facode = new javax.swing.JTextField();
        button_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("2FA - Insert Token");

        field_2facode.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        field_2facode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_2facode.setText("0000");

        button_login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        button_login.setText("Log in!");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_2facode, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(field_2facode, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_login, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        String code = field_2facode.getText();
        if ( code.isEmpty() ){
            new message_window(this,true,"Code field is empty","");
        }
        else{
            try{
                int data = Integer.parseInt(code);
                Parser parser = new Parser(connector.user_2fa_auth(data));
                if ( parser.get_flag() == 1 && parser.get_int("user_id") > 0){
                    connector.get_user_configuration(this);
                    new main_window(connector);
                    dispose();
                }
                else{
                    new message_window(this,true,"Wrong code.","");
                }
            }catch(NumberFormatException e){
                new message_window(this,true,"Code should be a number.","");
            } catch (UnirestException ex) {
                new message_window(this,true,"2FA Error\n"+ex.toString(),"ERROR");
            }
        }
    }//GEN-LAST:event_button_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login;
    private javax.swing.JTextField field_2facode;
    // End of variables declaration//GEN-END:variables
}
